export const COUNTRY_OPTIONS = [
  {value:'AFG',es:'Afganistán',en:'Afghanistan',de:'Afghanistan'},
  {value:'ALB',es:'Albania',en:'Albania',de:'Albanien'},
  {value:'DZA',es:'Argelia',en:'Algeria',de:'Algerien'},
  {value:'ASM',es:'Samoa Americana',en:'American Samoa',de:'Amerikanisch-Samoa'},
  {value:'AND',es:'Andorra',en:'Andorra',de:'Andorra'},
  {value:'AGO',es:'Angola',en:'Angola',de:'Angola'},
  {value:'AIA',es:'Anguila',en:'Anguilla',de:'Anguilla'},
  {value:'ATA',es:'Antártida',en:'Antarctica',de:'Antarktis'},
  {value:'ATG',es:'Antigua y Barbuda',en:'Antigua and Barbuda',de:'Antigua und Barbuda'},
  {value:'ARG',es:'Argentina',en:'Argentina',de:'Argentinien'},
  {value:'ARM',es:'Armenia',en:'Armenia',de:'Armenien'},
  {value:'ABW',es:'Aruba',en:'Aruba',de:'Aruba'},
  {value:'AUS',es:'Australia',en:'Australia',de:'Australien'},
  {value:'AUT',es:'Austria',en:'Austria',de:'Österreich'},
  {value:'AZE',es:'Azerbaiyán',en:'Azerbaijan',de:'Aserbaidschan'},
  {value:'BHS',es:'Bahamas',en:'Bahamas',de:'Bahamas'},
  {value:'BHR',es:'Baréin',en:'Bahrain',de:'Bahrain'},
  {value:'BGD',es:'Bangladés',en:'Bangladesh',de:'Bangladesch'},
  {value:'BRB',es:'Barbados',en:'Barbados',de:'Barbados'},
  {value:'BLR',es:'Bielorrusia',en:'Belarus',de:'Belarus'},
  {value:'BEL',es:'Bélgica',en:'Belgium',de:'Belgien'},
  {value:'BLZ',es:'Belice',en:'Belize',de:'Belize'},
  {value:'BEN',es:'Benín',en:'Benin',de:'Benin'},
  {value:'BMU',es:'Bermudas',en:'Bermuda',de:'Bermuda'},
  {value:'BTN',es:'Bután',en:'Bhutan',de:'Bhutan'},
  {value:'BOL',es:'Bolivia',en:'Bolivia',de:'Bolivien'},
  {value:'BES',es:'Bonaire, San Eustaquio y Saba',en:'Bonaire, Sint Eustatius and Saba',de:'Bonaire, Sint Eustatius und Saba'},
  {value:'BIH',es:'Bosnia y Herzegovina',en:'Bosnia and Herzegovina',de:'Bosnien und Herzegowina'},
  {value:'BWA',es:'Botsuana',en:'Botswana',de:'Botswana'},
  {value:'BVT',es:'Isla Bouvet',en:'Bouvet Island',de:'Bouvetinsel'},
  {value:'BRA',es:'Brasil',en:'Brazil',de:'Brasilien'},
  {value:'IOT',es:'Territorio Británico del Océano Índico',en:'British Indian Ocean Territory',de:'Britisches Territorium im Indischen Ozean'},
  {value:'BRN',es:'Brunéi',en:'Brunei Darussalam',de:'Brunei Darussalam'},
  {value:'BGR',es:'Bulgaria',en:'Bulgaria',de:'Bulgarien'},
  {value:'BFA',es:'Burkina Faso',en:'Burkina Faso',de:'Burkina Faso'},
  {value:'BDI',es:'Burundi',en:'Burundi',de:'Burundi'},
  {value:'CPV',es:'Cabo Verde',en:'Cabo Verde',de:'Cabo Verde'},
  {value:'KHM',es:'Camboya',en:'Cambodia',de:'Kambodscha'},
  {value:'CMR',es:'Camerún',en:'Cameroon',de:'Kamerun'},
  {value:'CAN',es:'Canadá',en:'Canada',de:'Kanada'},
  {value:'CYM',es:'Islas Caimán',en:'Cayman Islands',de:'Kaimaninseln'},
  {value:'CAF',es:'República Centroafricana',en:'Central African Republic',de:'Zentralafrikanische Republik'},
  {value:'TCD',es:'Chad',en:'Chad',de:'Tschad'},
  {value:'CHL',es:'Chile',en:'Chile',de:'Chile'},
  {value:'CHN',es:'China',en:'China',de:'China'},
  {value:'CXR',es:'Isla de Navidad',en:'Christmas Island',de:'Weihnachtsinsel'},
  {value:'CCK',es:'Islas Cocos',en:'Cocos (Keeling) Islands',de:'Kokosinseln'},
  {value:'COL',es:'Colombia',en:'Colombia',de:'Kolumbien'},
  {value:'COM',es:'Comoras',en:'Comoros',de:'Komoren'},
  {value:'COG',es:'Congo',en:'Congo',de:'Kongo'},
  {value:'COD',es:'República Democrática del Congo',en:'Democratic Republic of the Congo',de:'Demokratische Republik Kongo'},
  {value:'COK',es:'Islas Cook',en:'Cook Islands',de:'Cookinseln'},
  {value:'CRI',es:'Costa Rica',en:'Costa Rica',de:'Costa Rica'},
  {value:'CIV',es:'Costa de Marfil',en:"Côte d'Ivoire",de:'Côte d’Ivoire'},
  {value:'HRV',es:'Croacia',en:'Croatia',de:'Kroatien'},
  {value:'CUB',es:'Cuba',en:'Cuba',de:'Kuba'},
  {value:'CUW',es:'Curazao',en:'Curaçao',de:'Curaçao'},
  {value:'CYP',es:'Chipre',en:'Cyprus',de:'Zypern'},
  {value:'CZE',es:'Chequia',en:'Czechia',de:'Tschechien'},
  {value:'DNK',es:'Dinamarca',en:'Denmark',de:'Dänemark'},
  {value:'DJI',es:'Yibuti',en:'Djibouti',de:'Dschibuti'},
  {value:'DMA',es:'Dominica',en:'Dominica',de:'Dominica'},
  {value:'DOM',es:'República Dominicana',en:'Dominican Republic',de:'Dominikanische Republik'},
  {value:'ECU',es:'Ecuador',en:'Ecuador',de:'Ecuador'},
  {value:'EGY',es:'Egipto',en:'Egypt',de:'Ägypten'},
  {value:'SLV',es:'El Salvador',en:'El Salvador',de:'El Salvador'},
  {value:'GNQ',es:'Guinea Ecuatorial',en:'Equatorial Guinea',de:'Äquatorialguinea'},
  {value:'ERI',es:'Eritrea',en:'Eritrea',de:'Eritrea'},
  {value:'EST',es:'Estonia',en:'Estonia',de:'Estland'},
  {value:'SWZ',es:'Esuatini',en:'Eswatini',de:'Eswatini'},
  {value:'ETH',es:'Etiopía',en:'Ethiopia',de:'Äthiopien'},
  {value:'FLK',es:'Islas Malvinas',en:'Falkland Islands',de:'Falklandinseln'},
  {value:'FRO',es:'Islas Feroe',en:'Faroe Islands',de:'Färöer'},
  {value:'FJI',es:'Fiyi',en:'Fiji',de:'Fidschi'},
  {value:'FIN',es:'Finlandia',en:'Finland',de:'Finnland'},
  {value:'FRA',es:'Francia',en:'France',de:'Frankreich'},
  {value:'GUF',es:'Guayana Francesa',en:'French Guiana',de:'Französisch-Guayana'},
  {value:'PYF',es:'Polinesia Francesa',en:'French Polynesia',de:'Französisch-Polynesien'},
  {value:'ATF',es:'Territorios Australes Franceses',en:'French Southern Territories',de:'Französische Süd- und Antarktisgebiete'},
  {value:'GAB',es:'Gabón',en:'Gabon',de:'Gabun'},
  {value:'GMB',es:'Gambia',en:'Gambia',de:'Gambia'},
  {value:'GEO',es:'Georgia',en:'Georgia',de:'Georgien'},
  {value:'DEU',es:'Alemania',en:'Germany',de:'Deutschland'},
  {value:'GHA',es:'Ghana',en:'Ghana',de:'Ghana'},
  {value:'GIB',es:'Gibraltar',en:'Gibraltar',de:'Gibraltar'},
  {value:'GRC',es:'Grecia',en:'Greece',de:'Griechenland'},
  {value:'GRL',es:'Groenlandia',en:'Greenland',de:'Grönland'},
  {value:'GRD',es:'Granada',en:'Grenada',de:'Grenada'},
  {value:'GLP',es:'Guadalupe',en:'Guadeloupe',de:'Guadeloupe'},
  {value:'GUM',es:'Guam',en:'Guam',de:'Guam'},
  {value:'GTM',es:'Guatemala',en:'Guatemala',de:'Guatemala'},
  {value:'GGY',es:'Guernsey',en:'Guernsey',de:'Guernsey'},
  {value:'GIN',es:'Guinea',en:'Guinea',de:'Guinea'},
  {value:'GNB',es:'Guinea-Bisáu',en:'Guinea-Bissau',de:'Guinea-Bissau'},
  {value:'GUY',es:'Guyana',en:'Guyana',de:'Guyana'},
  {value:'HTI',es:'Haití',en:'Haiti',de:'Haiti'},
  {value:'HMD',es:'Islas Heard y McDonald',en:'Heard Island and McDonald Islands',de:'Heard und McDonaldinseln'},
  {value:'VAT',es:'Ciudad del Vaticano',en:'Holy See',de:'Vatikanstadt'},
  {value:'HND',es:'Honduras',en:'Honduras',de:'Honduras'},
  {value:'HKG',es:'Hong Kong',en:'Hong Kong',de:'Hongkong'},
  {value:'HUN',es:'Hungría',en:'Hungary',de:'Ungarn'},
  {value:'ISL',es:'Islandia',en:'Iceland',de:'Island'},
  {value:'IND',es:'India',en:'India',de:'Indien'},
  {value:'IDN',es:'Indonesia',en:'Indonesia',de:'Indonesien'},
  {value:'IRN',es:'Irán',en:'Iran',de:'Iran'},
  {value:'IRQ',es:'Irak',en:'Iraq',de:'Irak'},
  {value:'IRL',es:'Irlanda',en:'Ireland',de:'Irland'},
  {value:'IMN',es:'Isla de Man',en:'Isle of Man',de:'Isle of Man'},
  {value:'ISR',es:'Israel',en:'Israel',de:'Israel'},
  {value:'ITA',es:'Italia',en:'Italy',de:'Italien'},
  {value:'JAM',es:'Jamaica',en:'Jamaica',de:'Jamaika'},
  {value:'JPN',es:'Japón',en:'Japan',de:'Japan'},
  {value:'JEY',es:'Jersey',en:'Jersey',de:'Jersey'},
  {value:'JOR',es:'Jordania',en:'Jordan',de:'Jordanien'},
  {value:'KAZ',es:'Kazajistán',en:'Kazakhstan',de:'Kasachstan'},
  {value:'KEN',es:'Kenia',en:'Kenya',de:'Kenia'},
  {value:'KIR',es:'Kiribati',en:'Kiribati',de:'Kiribati'},
  {value:'PRK',es:'Corea del Norte',en:'North Korea',de:'Nordkorea'},
  {value:'KOR',es:'Corea del Sur',en:'South Korea',de:'Südkorea'},
  {value:'KWT',es:'Kuwait',en:'Kuwait',de:'Kuwait'},
  {value:'KGZ',es:'Kirguistán',en:'Kyrgyzstan',de:'Kirgisistan'},
  {value:'LAO',es:'Laos',en:'Laos',de:'Laos'},
  {value:'LVA',es:'Letonia',en:'Latvia',de:'Lettland'},
  {value:'LBN',es:'Líbano',en:'Lebanon',de:'Libanon'},
  {value:'LSO',es:'Lesoto',en:'Lesotho',de:'Lesotho'},
  {value:'LBR',es:'Liberia',en:'Liberia',de:'Liberia'},
  {value:'LBY',es:'Libia',en:'Libya',de:'Libyen'},
  {value:'LIE',es:'Liechtenstein',en:'Liechtenstein',de:'Liechtenstein'},
  {value:'LTU',es:'Lituania',en:'Lithuania',de:'Litauen'},
  {value:'LUX',es:'Luxemburgo',en:'Luxembourg',de:'Luxemburg'},
  {value:'MAC',es:'Macao',en:'Macao',de:'Macau'},
  {value:'MDG',es:'Madagascar',en:'Madagascar',de:'Madagaskar'},
  {value:'MWI',es:'Malaui',en:'Malawi',de:'Malawi'},
  {value:'MYS',es:'Malasia',en:'Malaysia',de:'Malaysia'},
  {value:'MDV',es:'Maldivas',en:'Maldives',de:'Malediven'},
  {value:'MLI',es:'Malí',en:'Mali',de:'Mali'},
  {value:'MLT',es:'Malta',en:'Malta',de:'Malta'},
  {value:'MHL',es:'Islas Marshall',en:'Marshall Islands',de:'Marshallinseln'},
  {value:'MTQ',es:'Martinica',en:'Martinique',de:'Martinique'},
  {value:'MRT',es:'Mauritania',en:'Mauritania',de:'Mauretanien'},
  {value:'MUS',es:'Mauricio',en:'Mauritius',de:'Mauritius'},
  {value:'MYT',es:'Mayotte',en:'Mayotte',de:'Mayotte'},
  {value:'MEX',es:'México',en:'Mexico',de:'Mexiko'},
  {value:'FSM',es:'Micronesia',en:'Micronesia',de:'Mikronesien'},
  {value:'MDA',es:'Moldavia',en:'Moldova',de:'Moldau'},
  {value:'MCO',es:'Mónaco',en:'Monaco',de:'Monaco'},
  {value:'MNG',es:'Mongolia',en:'Mongolia',de:'Mongolei'},
  {value:'MNE',es:'Montenegro',en:'Montenegro',de:'Montenegro'},
  {value:'MSR',es:'Montserrat',en:'Montserrat',de:'Montserrat'},
  {value:'MAR',es:'Marruecos',en:'Morocco',de:'Marokko'},
  {value:'MOZ',es:'Mozambique',en:'Mozambique',de:'Mosambik'},
  {value:'MMR',es:'Myanmar',en:'Myanmar',de:'Myanmar'},
  {value:'NAM',es:'Namibia',en:'Namibia',de:'Namibia'},
  {value:'NRU',es:'Nauru',en:'Nauru',de:'Nauru'},
  {value:'NPL',es:'Nepal',en:'Nepal',de:'Nepal'},
  {value:'NLD',es:'Países Bajos',en:'Netherlands',de:'Niederlande'},
  {value:'NCL',es:'Nueva Caledonia',en:'New Caledonia',de:'Neukaledonien'},
  {value:'NZL',es:'Nueva Zelanda',en:'New Zealand',de:'Neuseeland'},
  {value:'NIC',es:'Nicaragua',en:'Nicaragua',de:'Nicaragua'},
  {value:'NER',es:'Níger',en:'Niger',de:'Niger'},
  {value:'NGA',es:'Nigeria',en:'Nigeria',de:'Nigeria'},
  {value:'NIU',es:'Niue',en:'Niue',de:'Niue'},
  {value:'NFK',es:'Isla Norfolk',en:'Norfolk Island',de:'Norfolkinsel'},
  {value:'MKD',es:'Macedonia del Norte',en:'North Macedonia',de:'Nordmazedonien'},
  {value:'MNP',es:'Islas Marianas del Norte',en:'Northern Mariana Islands',de:'Nördliche Marianen'},
  {value:'NOR',es:'Noruega',en:'Norway',de:'Norwegen'},
  {value:'OMN',es:'Omán',en:'Oman',de:'Oman'},
  {value:'PAK',es:'Pakistán',en:'Pakistan',de:'Pakistan'},
  {value:'PLW',es:'Palaos',en:'Palau',de:'Palau'},
  {value:'PSE',es:'Palestina',en:'State of Palestine',de:'Palästina'},
  {value:'PAN',es:'Panamá',en:'Panama',de:'Panama'},
  {value:'PNG',es:'Papúa Nueva Guinea',en:'Papua New Guinea',de:'Papua-Neuguinea'},
  {value:'PRY',es:'Paraguay',en:'Paraguay',de:'Paraguay'},
  {value:'PER',es:'Perú',en:'Peru',de:'Peru'},
  {value:'PHL',es:'Filipinas',en:'Philippines',de:'Philippinen'},
  {value:'PCN',es:'Pitcairn',en:'Pitcairn',de:'Pitcairninseln'},
  {value:'POL',es:'Polonia',en:'Poland',de:'Polen'},
  {value:'PRT',es:'Portugal',en:'Portugal',de:'Portugal'},
  {value:'PRI',es:'Puerto Rico',en:'Puerto Rico',de:'Puerto Rico'},
  {value:'QAT',es:'Catar',en:'Qatar',de:'Katar'},
  {value:'REU',es:'Reunión',en:'Réunion',de:'Réunion'},
  {value:'ROU',es:'Rumanía',en:'Romania',de:'Rumänien'},
  {value:'RUS',es:'Rusia',en:'Russian Federation',de:'Russland'},
  {value:'RWA',es:'Ruanda',en:'Rwanda',de:'Ruanda'},
  {value:'BLM',es:'San Bartolomé',en:'Saint Barthélemy',de:'Saint-Barthélemy'},
  {value:'SHN',es:'Santa Elena, Ascensión y Tristán de Acuña',en:'Saint Helena, Ascension and Tristan da Cunha',de:'St. Helena, Ascension und Tristan da Cunha'},
  {value:'KNA',es:'San Cristóbal y Nieves',en:'Saint Kitts and Nevis',de:'St. Kitts und Nevis'},
  {value:'LCA',es:'Santa Lucía',en:'Saint Lucia',de:'St. Lucia'},
  {value:'MAF',es:'San Martín',en:'Saint Martin (French part)',de:'Saint-Martin'},
  {value:'SPM',es:'San Pedro y Miquelón',en:'Saint Pierre and Miquelon',de:'Saint-Pierre und Miquelon'},
  {value:'VCT',es:'San Vicente y las Granadinas',en:'Saint Vincent and the Grenadines',de:'St. Vincent und die Grenadinen'},
  {value:'WSM',es:'Samoa',en:'Samoa',de:'Samoa'},
  {value:'SMR',es:'San Marino',en:'San Marino',de:'San Marino'},
  {value:'STP',es:'Santo Tomé y Príncipe',en:'Sao Tome and Principe',de:'São Tomé und Príncipe'},
  {value:'SAU',es:'Arabia Saudí',en:'Saudi Arabia',de:'Saudi-Arabien'},
  {value:'SEN',es:'Senegal',en:'Senegal',de:'Senegal'},
  {value:'SRB',es:'Serbia',en:'Serbia',de:'Serbien'},
  {value:'SYC',es:'Seychelles',en:'Seychelles',de:'Seychellen'},
  {value:'SLE',es:'Sierra Leona',en:'Sierra Leone',de:'Sierra Leone'},
  {value:'SGP',es:'Singapur',en:'Singapore',de:'Singapur'},
  {value:'SXM',es:'Sint Maarten',en:'Sint Maarten (Dutch part)',de:'Sint Maarten'},
  {value:'SVK',es:'Eslovaquia',en:'Slovakia',de:'Slowakei'},
  {value:'SVN',es:'Eslovenia',en:'Slovenia',de:'Slowenien'},
  {value:'SLB',es:'Islas Salomón',en:'Solomon Islands',de:'Salomonen'},
  {value:'SOM',es:'Somalia',en:'Somalia',de:'Somalia'},
  {value:'ZAF',es:'Sudáfrica',en:'South Africa',de:'Südafrika'},
  {value:'SGS',es:'Georgia del Sur y las Islas Sandwich del Sur',en:'South Georgia and the South Sandwich Islands',de:'Südgeorgien und die Südlichen Sandwichinseln'},
  {value:'SSD',es:'Sudán del Sur',en:'South Sudan',de:'Südsudan'},
  {value:'ESP',es:'España',en:'Spain',de:'Spanien'},
  {value:'LKA',es:'Sri Lanka',en:'Sri Lanka',de:'Sri Lanka'},
  {value:'SDN',es:'Sudán',en:'Sudan',de:'Sudan'},
  {value:'SUR',es:'Surinam',en:'Suriname',de:'Suriname'},
  {value:'SJM',es:'Svalbard y Jan Mayen',en:'Svalbard and Jan Mayen',de:'Svalbard und Jan Mayen'},
  {value:'SWE',es:'Suecia',en:'Sweden',de:'Schweden'},
  {value:'CHE',es:'Suiza',en:'Switzerland',de:'Schweiz'},
  {value:'SYR',es:'Siria',en:'Syrian Arab Republic',de:'Syrien'},
  {value:'TWN',es:'Taiwán',en:'Taiwan',de:'Taiwan'},
  {value:'TJK',es:'Tayikistán',en:'Tajikistan',de:'Tadschikistan'},
  {value:'TZA',es:'Tanzania',en:'Tanzania',de:'Tansania'},
  {value:'THA',es:'Tailandia',en:'Thailand',de:'Thailand'},
  {value:'TLS',es:'Timor-Leste',en:'Timor-Leste',de:'Timor-Leste'},
  {value:'TGO',es:'Togo',en:'Togo',de:'Togo'},
  {value:'TKL',es:'Tokelau',en:'Tokelau',de:'Tokelau'},
  {value:'TON',es:'Tonga',en:'Tonga',de:'Tonga'},
  {value:'TTO',es:'Trinidad y Tobago',en:'Trinidad and Tobago',de:'Trinidad und Tobago'},
  {value:'TUN',es:'Túnez',en:'Tunisia',de:'Tunesien'},
  {value:'TUR',es:'Turquía',en:'Türkiye',de:'Türkei'},
  {value:'TKM',es:'Turkmenistán',en:'Turkmenistan',de:'Turkmenistan'},
  {value:'TCA',es:'Islas Turcas y Caicos',en:'Turks and Caicos Islands',de:'Turks- und Caicosinseln'},
  {value:'TUV',es:'Tuvalu',en:'Tuvalu',de:'Tuvalu'},
  {value:'UGA',es:'Uganda',en:'Uganda',de:'Uganda'},
  {value:'UKR',es:'Ucrania',en:'Ukraine',de:'Ukraine'},
  {value:'ARE',es:'Emiratos Árabes Unidos',en:'United Arab Emirates',de:'Vereinigte Arabische Emirate'},
  {value:'GBR',es:'Reino Unido',en:'United Kingdom',de:'Vereinigtes Königreich'},
  {value:'USA',es:'Estados Unidos',en:'United States',de:'Vereinigte Staaten'},
  {value:'UMI',es:'Islas Ultramarinas Menores de Estados Unidos',en:'United States Minor Outlying Islands',de:'Kleinere Amerikanische Überseeinseln'},
  {value:'URY',es:'Uruguay',en:'Uruguay',de:'Uruguay'},
  {value:'UZB',es:'Uzbekistán',en:'Uzbekistan',de:'Usbekistan'},
  {value:'VUT',es:'Vanuatu',en:'Vanuatu',de:'Vanuatu'},
  {value:'VEN',es:'Venezuela',en:'Venezuela',de:'Venezuela'},
  {value:'VNM',es:'Vietnam',en:'Viet Nam',de:'Vietnam'},
  {value:'VGB',es:'Islas Vírgenes Británicas',en:'British Virgin Islands',de:'Britische Jungferninseln'},
  {value:'VIR',es:'Islas Vírgenes de los Estados Unidos',en:'U.S. Virgin Islands',de:'Amerikanische Jungferninseln'},
  {value:'WLF',es:'Wallis y Futuna',en:'Wallis and Futuna',de:'Wallis und Futuna'},
  {value:'ESH',es:'Sáhara Occidental',en:'Western Sahara',de:'Westsahara'},
  {value:'YEM',es:'Yemen',en:'Yemen',de:'Jemen'},
  {value:'ZMB',es:'Zambia',en:'Zambia',de:'Sambia'},
  {value:'ZWE',es:'Zimbabue',en:'Zimbabwe',de:'Simbabwe'},
]
